// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnwohgkndhjflzyiqwng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNud29oZ2tuZGhqZmx6eWlxd25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTUxNTUsImV4cCI6MjA3MzM3MTE1NX0.Hq5leQCFAEKUP6tRA2300QBiwWcJJ1Zzoqld7ehSbuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});